### PR TITLE
full support for docker compose environment variables (closes #32)

### LINKED ISSUE #32: Full support for docker compose environment variables
I would like Harbor Compose to be able to read environment variables from docker-compose.yml files using [all of the supported methods](https://docs.docker.com/compose/environment-variables/).

### PR DESCRIPTION
**Pull request by jritsema**
Now using docker's [libcompose](https://github.com/docker/libcompose) library to parse the env vars.

Please don't check in secrets anymore.

See https://docs.docker.com/compose/environment-variables/

### CODE REVIEW

**Comment by jkurz** [comment]
are you not setting them as hidden if they are in the .env file? This is nice, but I think we still want to be able to determine if things should be hidden envVars or not right?

**Comment by wilsonodk** [comment]
Also, what about Discover Env Vars? Or, do we just say that Harbor Compose doesn't support Discover Env Vars?

**Comment by jritsema** [comment]
Making them hidden in Harbor is [a different feature](https://github.com/turnerlabs/harbor-compose/issues/19).  This is a good first step, to get them out of repos.  Some customers have asked for env_file support which this adds.

I've never used discover env vars since none of my customers are using them, but we can certainly add a feature for it.

**Comment by jkurz** [comment]
makes sense. Well this was a pretty simple change for the amount of functionality added. hardly any code was added to the repo. :) approved.

**Review by jkurz — APPROVED** [review]

**Pull request merged**
