### PR TITLE
Add godep

### PR DESCRIPTION
**Pull request by smithatlanta**

### CODE REVIEW

**Comment by jkurz** [comment]
lgtm

**Comment by wilsonodk** [comment]
lgtm

**Comment by smithatlanta** [comment]
So after talking to @jritsema it looks like we can get away without checking in the vendor directory by just doing a godep restore when you first pull down the project.  We will need to be careful when running godep save because it could update the other dependencies in the godeps.json file with newer revisions.  So in other works be careful when checking in the godeps.json file.

**Comment by wilsonodk** [comment]
Sounds like we need to add a "Contributions" section (or file) to this repo so that everyone understands how to work together.

**Comment by smithatlanta** [comment]
I agree, @wilsonodk

**Comment by jritsema** [comment]
So I think there was a miscommunication.  If we're going to use `godep` we need to commit /vendor.  This [issue](https://github.com/tools/godep/issues/50) confirms this.  We will also need to modify our Circle CI builds.  I will investigate that.

**Comment by smithatlanta** [comment]
I just reverted it back.

**Comment by jritsema** [comment]
Thanks @smithatlanta.  Couple of issues.  
- The tests don't work on my machine due to missing dependencies I think:

```
godep go test ./...

# github.com/turnerlabs/harbor-compose/cmd
cmd/harborAPI_test.go:9:2: cannot find package "github.com/stretchr/testify/assert" in any of:
    /Users/jritsema/code/gocode/src/github.com/turnerlabs/harbor-compose/vendor/github.com/stretchr/testify/assert (vendor tree)
    /usr/local/Cellar/go/1.6.2/libexec/src/github.com/stretchr/testify/assert (from $GOROOT)
    /Users/jritsema/code/gocode/src/github.com/turnerlabs/harbor-compose/Godeps/_workspace/src/github.com/stretchr/testify/assert (from $GOPATH)
    /Users/jritsema/code/gocode/src/github.com/stretchr/testify/assert
FAIL    github.com/turnerlabs/harbor-compose/cmd [setup failed]
?       github.com/turnerlabs/harbor-compose    [no test files]
?       github.com/turnerlabs/harbor-compose/vendor/github.com/howeyc/gopass    [no test files]
?       github.com/turnerlabs/harbor-compose/vendor/github.com/inconshreveable/mousetrap    [no test files]
?       github.com/turnerlabs/harbor-compose/vendor/github.com/jtacoma/uritemplates [no test files]
?       github.com/turnerlabs/harbor-compose/vendor/github.com/moul/http2curl   [no test files]
?       github.com/turnerlabs/harbor-compose/vendor/github.com/parnurzeal/gorequest [no test files]
?       github.com/turnerlabs/harbor-compose/vendor/github.com/spf13/cobra  [no test files]
?       github.com/turnerlabs/harbor-compose/vendor/github.com/spf13/pflag  [no test files]
?       github.com/turnerlabs/harbor-compose/vendor/golang.org/x/crypto/ssh/terminal    [no test files]
?       github.com/turnerlabs/harbor-compose/vendor/golang.org/x/net/publicsuffix   [no test files]
?       github.com/turnerlabs/harbor-compose/vendor/gopkg.in/yaml.v2    [no test files]
godep: go exit status 1
```
- Also these tests won't work when running on the public build server since they hit internal resources.  Should we use a mocking library?
- Seems odd that we're testing `github.com/turnerlabs/harbor-auth-client` when it's not actually being used in the project yet.
- I will update the build so that it will correctly run the tests and catch these types of things.

**Comment by smithatlanta** [comment]
For some reason, godep save didn't work correctly.  I just ran godep save ./... and the items were added to vendor and the json file so I'll check that in.

I will also comment out the harbor-auth-client dependency.

**Comment by jkurz** [comment]
@smithatlanta could we remove the tests for the auth-client? Those tests should live inside the auth-client itself. We should only be doing higher level integration tests in this repo. The low level functionality should be tested in the auth-client repo directly.

**Comment by smithatlanta** [comment]
It's not a test for the auth client per se but it's a test for the api that is using the auth client.   I commented it out but it can be removed.

Where should we do integration tests.  Eventually we need to test the api using the auth client.

**Comment by jritsema** [comment]
Looks like we're getting merge conflicts here now after merging the last PR into develop.  I resolved it locally, but it's not building due to changes from `go fmt`.  @jkurz, would you mind fixing the merge conflict and running `go fmt` before updating this PR?  Thanks.

Fyi, I've now got the circle ci build hopefully setup to build/test all feature branches from now on.  I don't think we can automatically run `go fmt` since it modifies code so I guess we'll need to ensure that all contributors run it before submitting a PR.  We'll add stuff like that to `CONTRIBUTING.md`.

**Pull request merged**
