### PR TITLE
Merge branch 'hotfix/v0.8.1' into develop

### PR DESCRIPTION
**Pull request by smithatlanta**
#58 
#61

### CODE REVIEW

**Comment by smithatlanta** [comment]
Is it possible to create a pull request for a branch as in login-changes into develop or can you only do PR's that go into master?  I have only done PR's into master in the past but maybe I'm missing something.

**Comment by wilsonodk** [comment]
Yes, you can do PRs into branches other than master. When you're creating the PR, just pick a different target. This works best when the branch's parent is the target of the PR.

```
master   +---+--------+----
             |
branch a     +--+---+------
                |   | <- your pr
branch p        +---+
```

**Comment by smithatlanta** [comment]
Need to play around with this.  I think the github gui by default does
master.

On Jan 2, 2017, at 2:45 PM, Wilson Wise <notifications@github.com> wrote:

Yes, you can do PRs into branches other than master. When you're creating
the PR, just pick a different target. This works best when the branch's
parent is the target of the PR.

master   +---+--------+----
             |
branch a     +--+---+------
                |   | <- your pr
branch p        +---+

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/turnerlabs/harbor-compose/pull/63#issuecomment-270013009>,
or mute the thread

**Comment by wilsonodk** [comment]
It definitely defaults to `master`, but you can change it.

**Comment by jritsema** [comment]
@smithatlanta, `v0.8.1` has [already been released](https://github.com/turnerlabs/harbor-compose/releases/tag/v0.8.1), but this can be `v0.8.2`.

Also, following the [release process](https://github.com/turnerlabs/harbor-compose/blob/master/CONTRIBUTING.md#release-process), you can submit your PR to target the `develop` branch (your branch is typically branched off develop) by simply picking that branch from the dropdown.  After the changes have been built, tested, and reviewed in develop, the release process involves creating a new branch (release or hotfix) off develop which gets merged to both master and develop.  I'm happy to do that release process if you want to create a new branch (from develop) and submit a new PR.

Thanks.

**Pull request closed without merging**
